# Generated by Django 4.1.3 on 2022-11-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_remove_comment_title_comment_tit_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tit',
            new_name='title',
        ),
    ]
