# Generated by Django 4.1.3 on 2022-11-10 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('women', '0007_like_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='author_1',
            field=models.ManyToManyField(related_name='books', through='women.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='women',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_books', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
