# Generated by Django 4.1.3 on 2022-11-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='owner',
        ),
    ]
