# Generated by Django 4.1.3 on 2022-11-12 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('women', '0019_alter_like_book_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='author',
            field=models.ManyToManyField(related_name='books', through='women.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
